#!/bin/bash
#
# kasutaja public kausta lisamise skript
# kasutaja nimi tuleb anda skripti parameetrina
#
# võime lisada ka kasutusjuhendi, kui midagi valesti käivitame või unustame kasutajanimi edasi anda.
# käsurea kaudu parameetrite arv on $# sees olev number, meie korral peab olema 1 parameeter - kasutajanimi
# kui aga antud parameeter ei ole lisatud - tuleb juhendada kasutajat, kuidas skriptiga tööd teha
if [ $# -ne 1 ]; then
	echo "kasutusjuhend: $0 kasutajanimi"
else
# defineerime vajalik muutuja kasutajanimi salvestamiseks
kasutajanimi=$1 # kuna andmed edastatakse käsurealt skripti parameetrina, siis need on $1 $2 jne
# lisame vajalik kataloog
# määrame vajalikud õigused
## nüüd on ainult üks rida aga hästi pikk
mkdir /home/$kasutajanimi/public && chown -R $kasutajanimi:$kasutajanimi /home/$kasutajanimi/public && chmod 751 /home/$kasutajanimi/public
## pika rea lõpp
#
# põhimõtteliselt nagu kõik, aga kes teab kas antud käsu tulemus on ok või mitte
#seega kontrollime seda
# $? - viimase! käsu väljund staatus, 0 kui on korras, muu kui on probleem
if [ $? -eq 0 ]; then
echo "Kasutaja nimega $kasutajanimi kodukaustas public loodud"
cat /etc/passwd | grep $kasutajanimi
else
echo "probleem kasutaja $kasutajanimi lisamisega"
echi "probleemi kood pn $?"
fi
#skripti õige kasutamise kontrolli lõpp
fi
