#!/bin/bash
failinimi=$1
if [ -f $failinimi -a -r $failinimi ]; then
echo "Fail on korras"
for nimi in $(cat $failinimi)
do
	#sellega peaks faili sisu olema nähtav, kui fail on kätte saadav ja nüüd echo asemel tuleb kutsuda vajalik skript
	# echo $rida
	sh lisa_kasutaja $nimi # sellega me lasme lisa_kasutaja skripti tööle
done
else
	echo "proibleem failiga $failinimi"
fi


